### ISSUE TITLE
Is HTTP custom data not supported?

### ISSUE THREAD

**Issue by galdalali** [placemark/placemark#68]
Hi,

I am trying to integrate my own custom data into a custom XYZ layer. The data itself is not secured and I usually approach it this way (just for an example):
`http://192.168.1.112:6062/BaseMap/TextureTiles/11/822/1218.jpg
`It won't load for some reason. 

However, the same data is loaded, just when it is secured:
`https://aws.XXXXXXXXX.com/BaseMap/TextureTiles/11/822/1218.jpg
`

Does loading http custom layers have any limitations?

**Comment by tordans** [comment]
AFAIK Mapbox GL JS / Maplibre GL JS does not support fetching data via http

**Comment by tmcw** [comment]
These tiles look like they're coming from your local network, so I can't test this fully, but the initial reason why this isn't working is because [Google Chrome blocks mixed content](https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html), and this is mixed content - play.placemark.io is HTTPS, and those tiles are HTTP.

If you go to site settings, and Allow insecure content, Chrome will load the tiles ( https://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content ) but I can't totally confirm that GL JS will display them.

**Comment by galdalali** [comment]
Yep, you are right. Testing was done using Edge browser (that was a mistake), with Chrome browser it worked right out of the box.

**Comment by tmcw** [comment]
Great, closing this out then - these browser restrictions would be hard to fix at the application level.
