### ISSUE TITLE
Drop packages/placemark-app

### ISSUE THREAD

**Issue by tmcw** [placemark/placemark#73]
I'm only working on `/play`. Those who are very interested could continue maintaining placemark-app, but simplicity is key and I think this repo should just be play.

**Comment by ohrie** [comment]
@tmcw  So do I understand you correct, that you want to drop the placemark-app package and not just move it to another repository inside the placemark organisation? Since it's standalone, I think the placemark orga would be the perfect place for the app, also as community project. Currently, we are using only the app, not play.

**Comment by tmcw** [comment]
All right, good point! I just moved that to https://github.com/placemark/placemark-fullstack - that'll have the fullstack app, this repo will have play.

**Comment by tmcw** [comment]
Done - this repo now contains `/play`, contains the fullstack setup: https://github.com/placemark/placemark-fullstack
